# website settings
website:
  title: "Leonardo S. Mateus Báez"                                # Your name
  description: "We shall defend our island, whatever the cost may be, we shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender."   # A brief slogan (optional)
#  image: img/logo.png
#  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - menu:
          - text: "Topographic Effect"
            href: projects/posts/topo/index.qmd
          - text: "Basin Effect"
            href: projects/posts/basin/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com/lsmateusb
      - icon: linkedin
        href: https://www.linkedin.com/in/lsmateusb/
      - icon: envelope
        aria-label: email
        href: "mailto:lsmateusb@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Lina Pérez</span>
    right: |
      <span class="faux-block"><a href="https://github.com/lmateus/LeonardoMateus">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - litera
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true